name: Update README with File List

on:
  push:
    branches:
      - main  # Passe an, falls dein Branch anders heißt

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Run update script
      run: python3 scripts/update_readme.py

    - name: Commit and push changes
      run: |
        git config user.name "AlexIsKing"
        git config user.email "alex_is_king@control-center.eu"
        git add README.md
        git commit -m "Auto: update README with file list" || echo "No changes to commit"
        git push
